In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
# load the diabetes dataset
diabetes = datasets.load_diabetes()

In [8]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8 , 9])
x[1:7:2]

array([1, 3, 5])

In [24]:
x = np.arange(9).reshape(3,3,1)
x

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]],

       [[6],
        [7],
        [8]]])

In [25]:
x[...,0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
x = np.arange(9).reshape(3, 3)

In [29]:
x[:,np.newaxis,]

array([[[0, 1, 2]],

       [[3, 4, 5]],

       [[6, 7, 8]]])